// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qtasnim_Digital_Teknologi.Data;

#nullable disable

namespace Qtasnim_Digital_Teknologi.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241008031540_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Qtasnim_Digital_Teknologi.Model.Inventory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("inventories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Test Object",
                            Name = "Pencil",
                            Quantity = 1
                        },
                        new
                        {
                            ID = 2,
                            Description = "Test Object",
                            Name = "Pen",
                            Quantity = 1
                        },
                        new
                        {
                            ID = 3,
                            Description = "Test Object",
                            Name = "Marker",
                            Quantity = 1
                        },
                        new
                        {
                            ID = 4,
                            Description = "Test Object",
                            Name = "Book",
                            Quantity = 1
                        },
                        new
                        {
                            ID = 5,
                            Description = "Test Object",
                            Name = "Box",
                            Quantity = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
