// <auto-generated />
using LibrarySys;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibrarySys.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20240918203112_AddPrimaryKeyToBook")]
    partial class AddPrimaryKeyToBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibrarySys.Models.Book", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Code = "JK-45",
                            Author = "J.K Rowling",
                            Stock = 1,
                            Title = "Harry Potter"
                        },
                        new
                        {
                            Code = "SHR-1",
                            Author = "Arthur Conan Doyle",
                            Stock = 1,
                            Title = "A Study in Scarlet"
                        },
                        new
                        {
                            Code = "TW-11",
                            Author = "Stephenie Meyer",
                            Stock = 1,
                            Title = "Twilight"
                        },
                        new
                        {
                            Code = "HOB-83",
                            Author = "J.R.R. Tolkien",
                            Stock = 1,
                            Title = "The Hobbit, or There and Back Again"
                        },
                        new
                        {
                            Code = "NRN-7",
                            Author = "C.S. Lewis",
                            Stock = 1,
                            Title = "The Lion, the Witch and the Wardrobe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
